version: 2
jobs:
  build:
    machine:
      image: "ubuntu-1604:201903-01"
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: "Set Python Version"
          command: pyenv global 3.7.0
      - run:
          command:  |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"
      - run:
          name: Testing
          command: |
            . env/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys
      - run:
          name: "Connect and Deploy"
          command: |
            echo '50.116.41.124 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBORweKXoNESafnKbyiNfHqfjfnturw3CiQOk2GQEal6xViB/I95OJWvk6ZIg++wM9EAW1/W32yUU1yKH+opA3tw=' >> ~/.ssh/known_hosts
            ssh sethangell@50.116.41.128 << 'ENDSSH'
            cd portfolio
            git pull
            source env/bin/activate
            python manage.py makemigrations
            python manage.py migrate
            ENDSSH
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
