version: 2
jobs:
  build:
    machine:
      image: "ubuntu-1604:201903-01"
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: "Set Python Version"
          command: pyenv global 3.7.0
      - run:
          command:  |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"
      - run:
          name: Testing
          command: |
            . env/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
