version: 2
jobs:
  build:
    machine:
      image: "ubuntu-1604:201903-01"
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: "Set Python Version"
          command: pyenv global 3.7.0
      - run:
          command:  |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"
      - run:
          name: Testing
          command: |
            . env/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys
      - run:
          name: "Connect and Deploy"
          command: |
            ssh -o StrictHostKeyChecking=no -vvv $SSH_USER@$SSH_HOST "./deploy_master.sh"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore:
                - develop
                - /sa-1-.*/