version: '3.8'

services:
  app:
    build: 
      context: ../app
      dockerfile: Dockerfile.prod
    command: gunicorn homepage.wsgi:application --bind 0.0.0.0:8000
    container_name: sethangell.com
    volumes: 
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file: ../prod.env