# Generated by Django 2.2.6 on 2020-01-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20200107_0317"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="html_body",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, max_length=256, unique=True),
        ),
    ]
