# Generated by Django 4.0.2 on 2022-03-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_topictags_rename_md_body_blogpost_markdown_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="preview",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
