# Generated by Django 4.0.2 on 2022-03-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_blogpost_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postimage",
            name="post",
        ),
        migrations.AlterField(
            model_name="postimage",
            name="reference",
            field=models.CharField(max_length=128),
        ),
    ]
