# Generated by Django 4.0.2 on 2022-03-11 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_remove_postimage_post_alter_postimage_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="header_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="blog.postimage",
            ),
        ),
    ]
