# Generated by Django 4.0.2 on 2022-03-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_blogpost_header_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="preview",
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
