# Generated by Django 4.0.2 on 2022-04-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_blogpost_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image_encoding",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="open_graph_protocol_description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
