# Generated by Django 4.0.2 on 2022-04-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_blogpost_image_encoding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postimage",
            name="thumbnail",
            field=models.ImageField(
                default=None, editable=False, upload_to="blog_images/thumbnails"
            ),
            preserve_default=False,
        ),
    ]
