# Generated by Django 2.2.6 on 2020-01-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191231_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='body',
            new_name='md_body',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='html_body',
            field=models.TextField(default='<h1>Waiting for conversion</h1>'),
            preserve_default=False,
        ),
    ]
