# Generated by Django 2.2.6 on 2020-07-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200724_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='preview',
            field=models.CharField(blank=True, max_length=360),
        ),
    ]
