# Generated by Django 2.2.6 on 2019-10-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("exp_id", models.AutoField(primary_key=True, serialize=False)),
                ("company", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=65)),
                ("description", models.TextField()),
                ("present", models.BooleanField()),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
            ],
        ),
    ]
